"""
Tests for the Heart Disease Predictor application
"""
import unittest
import sys
import os
from pathlib import Path

# Add the project root to the path
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))


class TestDataset(unittest.TestCase):
    """Test dataset loading and validation"""
    
    def test_hrlfm_dataset_exists(self):
        """Test that the HRLFM dataset file exists"""
        dataset_path = project_root / 'data' / 'cleaned_merged_heart_dataset.csv'
        self.assertTrue(dataset_path.exists(), "HRLFM dataset file should exist")
    
    def test_hrlfm_dataset_structure(self):
        """Test that the HRLFM dataset has correct structure"""
        import pandas as pd
        dataset_path = project_root / 'data' / 'cleaned_merged_heart_dataset.csv'
        df = pd.read_csv(dataset_path)
        
        # Check number of columns (13 features + 1 target = 14 columns)
        self.assertEqual(len(df.columns), 14, "Dataset should have 14 columns")
        
        # Check for target column
        self.assertIn('target', df.columns, "Dataset should have 'target' column")
        
        # Check number of samples (should be 1,888)
        self.assertGreater(len(df), 0, "Dataset should not be empty")
        self.assertGreater(len(df), 1000, "Dataset should have at least 1000 samples")
        self.assertEqual(len(df), 1888, "Dataset should have exactly 1,888 samples")
    
    def test_hrlfm_dataset_required_features(self):
        """Test that the HRLFM dataset has all required features"""
        import pandas as pd
        dataset_path = project_root / 'data' / 'cleaned_merged_heart_dataset.csv'
        df = pd.read_csv(dataset_path)
        
        required_features = [
            'age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 
            'restecg', 'thalachh', 'exang', 'oldpeak', 
            'slope', 'ca', 'thal', 'target'
        ]
        
        for feature in required_features:
            self.assertIn(feature, df.columns, f"Dataset should have '{feature}' column")


class TestModels(unittest.TestCase):
    """Test model functionality"""
    
    def test_models_can_be_loaded(self):
        """Test that models can be loaded if they exist"""
        import joblib
        
        models_dir = project_root / 'models'
        model_files = [
            'logistic_regression_model.pkl',
            'random_forest_model.pkl',
            'xgboost_model.pkl',
            'lightgbm_model.pkl',
            'svm_model.pkl',
            'voting_ensemble_model.pkl',
            'stacking_ensemble_model.pkl',
            'hrlfm_model.pkl',
            'best_model.pkl'
        ]
        
        # Only test if models exist (they're generated by running the training script)
        for model_file in model_files:
            model_path = models_dir / model_file
            if model_path.exists():
                try:
                    model = joblib.load(model_path)
                    self.assertIsNotNone(model, f"{model_file} should load successfully")
                except Exception as e:
                    self.fail(f"Failed to load {model_file}: {str(e)}")
    
    def test_preprocessing_objects_exist(self):
        """Test that preprocessing objects exist"""
        import joblib
        
        models_dir = project_root / 'models'
        preprocessing_files = [
            'scaler.pkl',
            'feature_names.pkl'
        ]
        
        for preproc_file in preprocessing_files:
            preproc_path = models_dir / preproc_file
            if preproc_path.exists():
                try:
                    obj = joblib.load(preproc_path)
                    self.assertIsNotNone(obj, f"{preproc_file} should load successfully")
                except Exception as e:
                    self.fail(f"Failed to load {preproc_file}: {str(e)}")


class TestStreamlitApp(unittest.TestCase):
    """Test Streamlit application"""
    
    def test_app_imports(self):
        """Test that the Streamlit app can be imported"""
        sys.path.insert(0, str(project_root / 'app'))
        try:
            import streamlit_app
            self.assertTrue(True, "App should import successfully")
        except ImportError as e:
            self.fail(f"Failed to import streamlit_app: {str(e)}")


if __name__ == '__main__':
    unittest.main()
